<?php
namespace ILAB_Aws\MTurk;

use ILAB_Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Mechanical Turk Requester Service** service.
 * @method \ILAB_Aws\Result acceptQualificationRequest(array $args = [])
 * @method \GuzzleHttp\Promise\Promise acceptQualificationRequestAsync(array $args = [])
 * @method \ILAB_Aws\Result approveAssignment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise approveAssignmentAsync(array $args = [])
 * @method \ILAB_Aws\Result associateQualificationWithWorker(array $args = [])
 * @method \GuzzleHttp\Promise\Promise associateQualificationWithWorkerAsync(array $args = [])
 * @method \ILAB_Aws\Result createAdditionalAssignmentsForHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAdditionalAssignmentsForHITAsync(array $args = [])
 * @method \ILAB_Aws\Result createHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createHITAsync(array $args = [])
 * @method \ILAB_Aws\Result createHITType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createHITTypeAsync(array $args = [])
 * @method \ILAB_Aws\Result createHITWithHITType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createHITWithHITTypeAsync(array $args = [])
 * @method \ILAB_Aws\Result createQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createQualificationTypeAsync(array $args = [])
 * @method \ILAB_Aws\Result createWorkerBlock(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createWorkerBlockAsync(array $args = [])
 * @method \ILAB_Aws\Result deleteHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteHITAsync(array $args = [])
 * @method \ILAB_Aws\Result deleteQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteQualificationTypeAsync(array $args = [])
 * @method \ILAB_Aws\Result deleteWorkerBlock(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteWorkerBlockAsync(array $args = [])
 * @method \ILAB_Aws\Result disassociateQualificationFromWorker(array $args = [])
 * @method \GuzzleHttp\Promise\Promise disassociateQualificationFromWorkerAsync(array $args = [])
 * @method \ILAB_Aws\Result getAccountBalance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAccountBalanceAsync(array $args = [])
 * @method \ILAB_Aws\Result getAssignment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getAssignmentAsync(array $args = [])
 * @method \ILAB_Aws\Result getFileUploadURL(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getFileUploadURLAsync(array $args = [])
 * @method \ILAB_Aws\Result getHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getHITAsync(array $args = [])
 * @method \ILAB_Aws\Result getQualificationScore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getQualificationScoreAsync(array $args = [])
 * @method \ILAB_Aws\Result getQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getQualificationTypeAsync(array $args = [])
 * @method \ILAB_Aws\Result listAssignmentsForHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listAssignmentsForHITAsync(array $args = [])
 * @method \ILAB_Aws\Result listBonusPayments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listBonusPaymentsAsync(array $args = [])
 * @method \ILAB_Aws\Result listHITs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listHITsAsync(array $args = [])
 * @method \ILAB_Aws\Result listHITsForQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listHITsForQualificationTypeAsync(array $args = [])
 * @method \ILAB_Aws\Result listQualificationRequests(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listQualificationRequestsAsync(array $args = [])
 * @method \ILAB_Aws\Result listQualificationTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listQualificationTypesAsync(array $args = [])
 * @method \ILAB_Aws\Result listReviewPolicyResultsForHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listReviewPolicyResultsForHITAsync(array $args = [])
 * @method \ILAB_Aws\Result listReviewableHITs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listReviewableHITsAsync(array $args = [])
 * @method \ILAB_Aws\Result listWorkerBlocks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkerBlocksAsync(array $args = [])
 * @method \ILAB_Aws\Result listWorkersWithQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkersWithQualificationTypeAsync(array $args = [])
 * @method \ILAB_Aws\Result notifyWorkers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise notifyWorkersAsync(array $args = [])
 * @method \ILAB_Aws\Result rejectAssignment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise rejectAssignmentAsync(array $args = [])
 * @method \ILAB_Aws\Result rejectQualificationRequest(array $args = [])
 * @method \GuzzleHttp\Promise\Promise rejectQualificationRequestAsync(array $args = [])
 * @method \ILAB_Aws\Result sendBonus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sendBonusAsync(array $args = [])
 * @method \ILAB_Aws\Result sendTestEventNotification(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sendTestEventNotificationAsync(array $args = [])
 * @method \ILAB_Aws\Result updateExpirationForHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateExpirationForHITAsync(array $args = [])
 * @method \ILAB_Aws\Result updateHITReviewStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateHITReviewStatusAsync(array $args = [])
 * @method \ILAB_Aws\Result updateHITTypeOfHIT(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateHITTypeOfHITAsync(array $args = [])
 * @method \ILAB_Aws\Result updateNotificationSettings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateNotificationSettingsAsync(array $args = [])
 * @method \ILAB_Aws\Result updateQualificationType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateQualificationTypeAsync(array $args = [])
 */
class MTurkClient extends AwsClient {}
